### ISSUE TITLE
Support for custom new_release version

### ISSUE THREAD

**Issue by JustSimplyKyle** [ATiltedTree/create-aur-release#2]
#### Current Behavior

This as you see doesn't work.
https://github.com/RPMTW/RPMLauncher/actions/runs/2323945064

Should not error.
#### Additional context/Screenshots

The version number should be this `${{ secrets.VERSION  }}+${{ github.run_number }}`
#### Possible Solution

Add support for custom new_release, and it's an optional one.
If the user doesn't choose to give one, then use the current method

**Comment by KyleUltimate** [comment]
I made it!
https://github.com/KyleUltimate/upgrade-aur-package

**Comment by KyleUltimate** [comment]
The only actual "code" added is
```bash
if [[ -z "${INPUT_VERSION}" ]]; then
  NEW_RELEASE=${GITHUB_REF##*/v}
else
  NEW_RELEASE=${INPUT_VERSION}
fi
```
